//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sappan.CryptoPAn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sappan.CryptoPAn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IPv4 address must comprise four bytes..
        /// </summary>
        internal static string ErrorIPv4TooShort {
            get {
                return ResourceManager.GetString("ErrorIPv4TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An IPv6 address must comprise 16 bytes..
        /// </summary>
        internal static string ErrorIPv6TooShort {
            get {
                return ResourceManager.GetString("ErrorIPv6TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given Crypto-PAn key is too short..
        /// </summary>
        internal static string ErrorKeyTooShort {
            get {
                return ResourceManager.GetString("ErrorKeyTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given cryptographic algorithm is not initialised with a valid initial vector..
        /// </summary>
        internal static string ErrorNoIV {
            get {
                return ResourceManager.GetString("ErrorNoIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given cryptographic algorithm is not initialised with a valid key..
        /// </summary>
        internal static string ErrorNoKey {
            get {
                return ResourceManager.GetString("ErrorNoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the pad passed to the anoymiser must match the length of the key..
        /// </summary>
        internal static string ErrorPadLength {
            get {
                return ResourceManager.GetString("ErrorPadLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified address family is not supported for pseudonymisation..
        /// </summary>
        internal static string ErrorUnsupportedFamily {
            get {
                return ResourceManager.GetString("ErrorUnsupportedFamily", resourceCulture);
            }
        }
    }
}
