//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sappan.JsonAnyonmiser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sappan.JsonAnyonmiser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file must be passed as first command line argument..
        /// </summary>
        internal static string ErrorConfigMissing {
            get {
                return ResourceManager.GetString("ErrorConfigMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string encryption key must comprise at least {0} characters..
        /// </summary>
        internal static string ErrorKeyTooShort {
            get {
                return ResourceManager.GetString("ErrorKeyTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source file or directory &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string ErrorSourceMissing {
            get {
                return ResourceManager.GetString("ErrorSourceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Crypto-PAn key &quot;{0}&quot;..
        /// </summary>
        internal static string MsgCryptoPAnKey {
            get {
                return ResourceManager.GetString("MsgCryptoPAnKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating random Crypto-PAn key..
        /// </summary>
        internal static string MsgGenerateCryptoPAnKey {
            get {
                return ResourceManager.GetString("MsgGenerateCryptoPAnKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating random string encryption key..
        /// </summary>
        internal static string MsgGenerateStringKey {
            get {
                return ResourceManager.GetString("MsgGenerateStringKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is a directory. Process all files matching the pattern &quot;{1}&quot;..
        /// </summary>
        internal static string MsgProcessingDirectory {
            get {
                return ResourceManager.GetString("MsgProcessingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing input from &quot;{0}&quot;..
        /// </summary>
        internal static string MsgSourcePath {
            get {
                return ResourceManager.GetString("MsgSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using string encryption key &quot;{0}&quot;..
        /// </summary>
        internal static string MsgStringCryptoKey {
            get {
                return ResourceManager.GetString("MsgStringCryptoKey", resourceCulture);
            }
        }
    }
}
